# Generated by Django 2.2.16 on 2022-04-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('MODERATOR', 'moderator')], default='ADMIN', max_length=2),
        ),
    ]
