# Generated by Django 2.2.16 on 2022-04-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('MODERATOR', 'moderator'), ('USER', 'user')], default='USER', max_length=2),
        ),
    ]
