# Generated by Django 2.2.16 on 2022-04-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220420_0915'),
        ('reviews', '0005_auto_20220419_2228'),
    ]

    operations = [
    ]
