# Generated by Django 2.2.16 on 2022-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220414_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='confirmation_code'),
        ),
    ]
